server:
  port: 8080
  name: pureframe

#自定义参数
demoprop:
  name: ${server.name}
  sex: ${random.int[0,1]}

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/demo?allowMultiQueries=true
        username: root
        password: root
info:
  service-info: smart_home_service
  api-doc: /swagger-ui.html
swagger:
  basePath: com.ligw
  title: pureframe 提供的API信息
  description: API信息有疑问请联系相关开发人员
  contact: ligw
  version: @project.version@
