# 本地开发，请配置idea启动参数Active Profile = dev, 或增加vm参数-Dspring.profiles.active=dev, springboot程序会读取使用application-dev.yml的配置
server:
    port: 8080
    name: java-start
    servlet:
        context-path: /java-start

log:
    path: /data/java-start

# database, 多数据源：db1、db2
jdbc:
    db1:
        driverClassName: com.mysql.jdbc.Driver
        validationQuery: SELECT 1 FROM DUAL
        url: ${JDBC_DB1_URL}
        username: ${JDBC_DB1_USERNAME}
        password: ${JDBC_DB1_PASSWORD}